using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

#pragma warning disable CA1814 // Prefer jagged arrays over multidimensional

namespace Infrastructure.Data.Migrations
{
    /// <inheritdoc />
    public partial class init : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.EnsureSchema(
                name: "User");

            migrationBuilder.CreateTable(
                name: "AspNetRoles",
                schema: "User",
                columns: table => new
                {
                    Id = table.Column<long>(type: "bigint", nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    Name = table.Column<string>(type: "nvarchar(256)", maxLength: 256, nullable: true),
                    NormalizedName = table.Column<string>(type: "nvarchar(256)", maxLength: 256, nullable: true),
                    ConcurrencyStamp = table.Column<string>(type: "nvarchar(max)", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_AspNetRoles", x => x.Id);
                });

            migrationBuilder.CreateTable(
                name: "AspNetUsers",
                schema: "User",
                columns: table => new
                {
                    FullName = table.Column<string>(type: "NVARCHAR(50)", nullable: false),
                    ICNumber = table.Column<string>(type: "nvarchar(30)", nullable: false),
                    LanguageID = table.Column<int>(type: "int", nullable: false),
                    Salt = table.Column<string>(type: "nvarchar(500)", nullable: true),
                    PINHash = table.Column<string>(type: "nvarchar(500)", nullable: true),
                    MobileOTPHash = table.Column<string>(type: "nvarchar(500)", nullable: true),
                    EmailOTPHash = table.Column<string>(type: "nvarchar(500)", nullable: true),
                    Id = table.Column<long>(type: "bigint", nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    MobileOTPSentAt = table.Column<DateTime>(type: "datetime2", nullable: true),
                    EmailOTPSentAt = table.Column<DateTime>(type: "datetime2", nullable: true),
                    Status = table.Column<int>(type: "int", nullable: false),
                    CreatedAt = table.Column<DateTime>(type: "datetime2", nullable: false),
                    UpdatedAt = table.Column<DateTime>(type: "datetime2", nullable: true),
                    CreatedBy = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    UpdatedBy = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    UserName = table.Column<string>(type: "nvarchar(256)", maxLength: 256, nullable: true),
                    NormalizedUserName = table.Column<string>(type: "nvarchar(256)", maxLength: 256, nullable: true),
                    Email = table.Column<string>(type: "nvarchar(256)", maxLength: 256, nullable: true),
                    NormalizedEmail = table.Column<string>(type: "nvarchar(256)", maxLength: 256, nullable: true),
                    EmailConfirmed = table.Column<bool>(type: "bit", nullable: false),
                    PasswordHash = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    SecurityStamp = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    ConcurrencyStamp = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    PhoneNumber = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    PhoneNumberConfirmed = table.Column<bool>(type: "bit", nullable: false),
                    TwoFactorEnabled = table.Column<bool>(type: "bit", nullable: false),
                    LockoutEnd = table.Column<DateTimeOffset>(type: "datetimeoffset", nullable: true),
                    LockoutEnabled = table.Column<bool>(type: "bit", nullable: false),
                    AccessFailedCount = table.Column<int>(type: "int", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_AspNetUsers", x => x.Id);
                });

            migrationBuilder.CreateTable(
                name: "Dictionaries",
                schema: "User",
                columns: table => new
                {
                    ID = table.Column<int>(type: "int", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Dictionaries", x => x.ID);
                });

            migrationBuilder.CreateTable(
                name: "Languages",
                schema: "User",
                columns: table => new
                {
                    ID = table.Column<int>(type: "int", nullable: false),
                    LanguageName = table.Column<string>(type: "nvarchar(10)", nullable: false),
                    Description = table.Column<string>(type: "nvarchar(20)", nullable: false),
                    Direction = table.Column<string>(type: "nvarchar(20)", nullable: false),
                    Culture = table.Column<string>(type: "nvarchar(10)", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Languages", x => x.ID);
                });

            migrationBuilder.CreateTable(
                name: "AspNetRoleClaims",
                schema: "User",
                columns: table => new
                {
                    Id = table.Column<int>(type: "int", nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    RoleId = table.Column<long>(type: "bigint", nullable: false),
                    ClaimType = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    ClaimValue = table.Column<string>(type: "nvarchar(max)", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_AspNetRoleClaims", x => x.Id);
                    table.ForeignKey(
                        name: "FK_AspNetRoleClaims_AspNetRoles_RoleId",
                        column: x => x.RoleId,
                        principalSchema: "User",
                        principalTable: "AspNetRoles",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateTable(
                name: "AspNetUserClaims",
                schema: "User",
                columns: table => new
                {
                    Id = table.Column<int>(type: "int", nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    UserId = table.Column<long>(type: "bigint", nullable: false),
                    ClaimType = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    ClaimValue = table.Column<string>(type: "nvarchar(max)", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_AspNetUserClaims", x => x.Id);
                    table.ForeignKey(
                        name: "FK_AspNetUserClaims_AspNetUsers_UserId",
                        column: x => x.UserId,
                        principalSchema: "User",
                        principalTable: "AspNetUsers",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateTable(
                name: "AspNetUserLogins",
                schema: "User",
                columns: table => new
                {
                    LoginProvider = table.Column<string>(type: "nvarchar(450)", nullable: false),
                    ProviderKey = table.Column<string>(type: "nvarchar(450)", nullable: false),
                    ProviderDisplayName = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    UserId = table.Column<long>(type: "bigint", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_AspNetUserLogins", x => new { x.LoginProvider, x.ProviderKey });
                    table.ForeignKey(
                        name: "FK_AspNetUserLogins_AspNetUsers_UserId",
                        column: x => x.UserId,
                        principalSchema: "User",
                        principalTable: "AspNetUsers",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateTable(
                name: "AspNetUserRoles",
                schema: "User",
                columns: table => new
                {
                    UserId = table.Column<long>(type: "bigint", nullable: false),
                    RoleId = table.Column<long>(type: "bigint", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_AspNetUserRoles", x => new { x.UserId, x.RoleId });
                    table.ForeignKey(
                        name: "FK_AspNetUserRoles_AspNetRoles_RoleId",
                        column: x => x.RoleId,
                        principalSchema: "User",
                        principalTable: "AspNetRoles",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                    table.ForeignKey(
                        name: "FK_AspNetUserRoles_AspNetUsers_UserId",
                        column: x => x.UserId,
                        principalSchema: "User",
                        principalTable: "AspNetUsers",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateTable(
                name: "AspNetUserTokens",
                schema: "User",
                columns: table => new
                {
                    UserId = table.Column<long>(type: "bigint", nullable: false),
                    LoginProvider = table.Column<string>(type: "nvarchar(450)", nullable: false),
                    Name = table.Column<string>(type: "nvarchar(450)", nullable: false),
                    Value = table.Column<string>(type: "nvarchar(max)", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_AspNetUserTokens", x => new { x.UserId, x.LoginProvider, x.Name });
                    table.ForeignKey(
                        name: "FK_AspNetUserTokens_AspNetUsers_UserId",
                        column: x => x.UserId,
                        principalSchema: "User",
                        principalTable: "AspNetUsers",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateTable(
                name: "DictionaryLocalizations",
                schema: "User",
                columns: table => new
                {
                    ID = table.Column<int>(type: "int", nullable: false),
                    LanguageID = table.Column<int>(type: "int", nullable: false),
                    Description = table.Column<string>(type: "nvarchar(max)", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_DictionaryLocalizations", x => new { x.ID, x.LanguageID });
                    table.ForeignKey(
                        name: "FK_DictionaryLocalizations_Dictionaries_ID",
                        column: x => x.ID,
                        principalSchema: "User",
                        principalTable: "Dictionaries",
                        principalColumn: "ID",
                        onDelete: ReferentialAction.Cascade);
                    table.ForeignKey(
                        name: "FK_DictionaryLocalizations_Languages_LanguageID",
                        column: x => x.LanguageID,
                        principalSchema: "User",
                        principalTable: "Languages",
                        principalColumn: "ID",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.InsertData(
                schema: "User",
                table: "Dictionaries",
                column: "ID",
                values: new object[]
                {
                    0,
                    1,
                    2,
                    3,
                    4,
                    5,
                    6,
                    7,
                    8,
                    9,
                    10,
                    11,
                    12,
                    13,
                    14,
                    15,
                    16,
                    17,
                    18,
                    19,
                    20,
                    21,
                    22,
                    23,
                    24,
                    25,
                    26,
                    27,
                    28,
                    29,
                    30,
                    31,
                    32,
                    33,
                    34,
                    35,
                    36,
                    37,
                    38,
                    39,
                    40,
                    41,
                    42,
                    43,
                    44,
                    45,
                    46,
                    47,
                    48,
                    49,
                    50,
                    51,
                    52,
                    53,
                    54,
                    55,
                    56,
                    57,
                    58,
                    59,
                    60,
                    61,
                    62,
                    63,
                    64,
                    65,
                    66,
                    67,
                    68,
                    69,
                    70,
                    71,
                    72,
                    73,
                    74,
                    75,
                    76,
                    77,
                    78,
                    79,
                    80,
                    81,
                    82,
                    83,
                    84,
                    85,
                    86,
                    87,
                    88,
                    89,
                    90,
                    91,
                    92,
                    93,
                    94,
                    95,
                    96,
                    97,
                    98,
                    99,
                    100,
                    101,
                    102,
                    103,
                    104,
                    105,
                    106,
                    107,
                    108,
                    109,
                    110,
                    111,
                    112,
                    113,
                    114,
                    115,
                    116,
                    117,
                    118,
                    119,
                    120,
                    121,
                    122,
                    123,
                    124,
                    125,
                    126,
                    127,
                    128,
                    129,
                    130,
                    131,
                    132,
                    133,
                    134,
                    135,
                    136,
                    137,
                    138,
                    139,
                    140,
                    141,
                    142,
                    143,
                    144,
                    145,
                    146,
                    147,
                    148,
                    149,
                    150,
                    151,
                    152,
                    153,
                    154,
                    155,
                    156,
                    157,
                    158,
                    159,
                    160,
                    161,
                    162,
                    163,
                    164,
                    165,
                    166,
                    167,
                    168,
                    169,
                    170,
                    171,
                    172,
                    173,
                    174,
                    175,
                    176,
                    177,
                    178,
                    179,
                    180,
                    181,
                    182,
                    183,
                    184,
                    185,
                    186,
                    187,
                    188,
                    189,
                    190,
                    191,
                    192,
                    193,
                    194,
                    195,
                    196,
                    197,
                    198,
                    199,
                    200,
                    201,
                    202,
                    203,
                    204,
                    205,
                    206,
                    207,
                    208,
                    209,
                    210,
                    211,
                    212,
                    213,
                    214,
                    215,
                    216,
                    217,
                    218,
                    219,
                    220,
                    221,
                    222,
                    223,
                    224,
                    225,
                    226,
                    227,
                    228,
                    229,
                    230,
                    231,
                    232,
                    233,
                    234,
                    235,
                    236,
                    237,
                    238,
                    239,
                    240,
                    241,
                    242,
                    243,
                    244,
                    245,
                    246,
                    247,
                    248,
                    249,
                    250,
                    251,
                    252,
                    253,
                    254,
                    255,
                    256,
                    257,
                    258,
                    259,
                    260,
                    261,
                    262,
                    263,
                    264,
                    265,
                    266,
                    267,
                    268,
                    269,
                    270,
                    271,
                    272,
                    273,
                    274,
                    275,
                    276,
                    277,
                    278,
                    279,
                    280,
                    281,
                    282,
                    283,
                    284,
                    285,
                    286,
                    287,
                    288,
                    289,
                    290,
                    291,
                    292,
                    293,
                    294,
                    295,
                    296,
                    297,
                    298,
                    299,
                    300,
                    301,
                    302,
                    303,
                    304,
                    305,
                    306,
                    307,
                    308,
                    309,
                    310,
                    311,
                    312,
                    313,
                    314,
                    315,
                    316,
                    317,
                    318,
                    319,
                    320,
                    321,
                    322,
                    323,
                    324,
                    325,
                    326,
                    327,
                    328,
                    329,
                    330,
                    331,
                    332,
                    333,
                    334,
                    335,
                    336,
                    337,
                    338,
                    339,
                    340,
                    341,
                    342,
                    343,
                    344,
                    345,
                    346,
                    347,
                    348,
                    349,
                    350,
                    351,
                    352,
                    353,
                    354,
                    355,
                    356,
                    357,
                    358,
                    359,
                    360,
                    361,
                    362,
                    363,
                    364,
                    365,
                    366,
                    367,
                    368,
                    369,
                    370,
                    371,
                    372,
                    373,
                    374,
                    375,
                    376,
                    377,
                    378,
                    379,
                    380,
                    381,
                    382,
                    383,
                    384,
                    385,
                    386,
                    387,
                    388,
                    389,
                    390,
                    391,
                    392,
                    393,
                    394,
                    395,
                    396,
                    397,
                    398,
                    399,
                    400,
                    401,
                    402,
                    403,
                    404,
                    405,
                    406,
                    407,
                    408,
                    409,
                    410,
                    411,
                    412,
                    413,
                    414,
                    415,
                    416,
                    417,
                    418,
                    419,
                    420,
                    421,
                    422,
                    423,
                    424,
                    425,
                    426,
                    427,
                    428,
                    429,
                    430,
                    431,
                    432,
                    433,
                    434,
                    435,
                    436,
                    437,
                    438,
                    439,
                    440,
                    441,
                    442,
                    443,
                    444,
                    445,
                    446,
                    447,
                    448,
                    449,
                    450,
                    451,
                    452,
                    453,
                    454,
                    455,
                    456,
                    457,
                    458,
                    459,
                    460,
                    461,
                    462,
                    463,
                    464,
                    465,
                    466,
                    467,
                    468,
                    469,
                    470,
                    471,
                    472,
                    473,
                    474,
                    475,
                    476,
                    477,
                    478,
                    479,
                    480,
                    481,
                    482,
                    483,
                    484,
                    485,
                    486,
                    487,
                    488,
                    489,
                    490,
                    491,
                    492,
                    493,
                    494,
                    495,
                    496,
                    497,
                    498,
                    499,
                    500,
                    501,
                    502,
                    503,
                    504,
                    505,
                    506,
                    507,
                    508,
                    509,
                    510,
                    511,
                    512,
                    513,
                    514,
                    515,
                    516,
                    517,
                    518,
                    519,
                    520,
                    521,
                    522,
                    523,
                    524,
                    525,
                    526,
                    527,
                    528,
                    529,
                    530,
                    531,
                    532,
                    533,
                    534,
                    535,
                    536,
                    537,
                    538,
                    539,
                    540,
                    541,
                    542,
                    543,
                    544,
                    545,
                    546,
                    547,
                    548,
                    549,
                    550,
                    551,
                    552,
                    553,
                    554,
                    555,
                    556,
                    557,
                    558,
                    559,
                    560,
                    561,
                    562,
                    563,
                    564,
                    565,
                    566,
                    567,
                    568,
                    569,
                    570,
                    571,
                    572,
                    573,
                    574,
                    575,
                    576,
                    577,
                    578,
                    579,
                    580,
                    581,
                    582,
                    583,
                    584,
                    585,
                    586,
                    587,
                    588,
                    589,
                    590,
                    591,
                    592,
                    593,
                    594,
                    595,
                    596,
                    597,
                    598,
                    599,
                    600,
                    601,
                    602,
                    603,
                    604,
                    605,
                    606,
                    607,
                    608,
                    609,
                    610,
                    611,
                    612,
                    613,
                    614,
                    615,
                    616,
                    617,
                    618,
                    619,
                    620,
                    621,
                    622,
                    623,
                    624,
                    625,
                    626,
                    627,
                    628,
                    629,
                    630,
                    631,
                    632,
                    633,
                    634,
                    635,
                    636,
                    637,
                    638,
                    639,
                    640,
                    641,
                    642,
                    643,
                    644,
                    645,
                    646,
                    647,
                    648,
                    649,
                    650,
                    651,
                    652,
                    653,
                    654,
                    655,
                    656,
                    657,
                    658,
                    659,
                    660,
                    661,
                    662,
                    663,
                    664,
                    665,
                    666,
                    667,
                    668,
                    669,
                    670,
                    671,
                    672,
                    673,
                    674,
                    675,
                    676,
                    677,
                    678,
                    679,
                    680,
                    681,
                    682,
                    683,
                    684,
                    685,
                    686,
                    687,
                    688,
                    689,
                    690,
                    691,
                    692,
                    693,
                    694,
                    695,
                    696,
                    697,
                    698,
                    699,
                    700,
                    701,
                    702,
                    703,
                    704,
                    705,
                    706,
                    707,
                    708,
                    709,
                    710,
                    711,
                    712,
                    713,
                    714,
                    715,
                    716,
                    717,
                    718,
                    719,
                    720,
                    721,
                    722,
                    723,
                    724,
                    725,
                    726,
                    727,
                    728,
                    729,
                    730,
                    731,
                    732,
                    733,
                    734,
                    735,
                    736,
                    737,
                    738,
                    739,
                    740,
                    741,
                    742,
                    743,
                    744,
                    745,
                    746,
                    747,
                    748,
                    749,
                    750,
                    751,
                    752,
                    753,
                    754,
                    755,
                    756,
                    757,
                    758,
                    759,
                    760,
                    761,
                    762,
                    763,
                    764,
                    765,
                    766,
                    767,
                    768,
                    769,
                    770,
                    771,
                    772,
                    773,
                    774,
                    775,
                    776,
                    777,
                    778,
                    779,
                    780,
                    781,
                    782,
                    783,
                    784,
                    785,
                    786,
                    787,
                    788,
                    789,
                    790,
                    791,
                    792,
                    793,
                    794,
                    795,
                    796,
                    797,
                    798,
                    799,
                    800,
                    801,
                    802,
                    803,
                    804,
                    805,
                    806,
                    807,
                    808,
                    809,
                    810,
                    811,
                    812,
                    813,
                    814,
                    815,
                    816,
                    817,
                    818,
                    819,
                    820,
                    821,
                    822,
                    823,
                    824,
                    825,
                    826,
                    827,
                    828,
                    829,
                    830,
                    831,
                    832,
                    833,
                    834,
                    835,
                    836,
                    837,
                    838,
                    839,
                    840,
                    841,
                    842,
                    843,
                    844,
                    845,
                    846,
                    847,
                    848,
                    849,
                    850,
                    851,
                    852,
                    853,
                    854,
                    855,
                    856,
                    857,
                    858,
                    859,
                    860,
                    861,
                    862,
                    863,
                    864,
                    865,
                    866,
                    867,
                    868,
                    869,
                    870,
                    871,
                    872,
                    873,
                    874,
                    875,
                    876,
                    877,
                    878,
                    879,
                    880,
                    881,
                    882,
                    883,
                    884,
                    885,
                    886,
                    887,
                    888,
                    889,
                    890,
                    891,
                    892,
                    893,
                    894,
                    895,
                    896,
                    897,
                    898,
                    899,
                    900,
                    901,
                    902,
                    903,
                    904,
                    905,
                    906,
                    907,
                    908,
                    909,
                    910,
                    911,
                    912,
                    913,
                    914,
                    915,
                    916,
                    917,
                    918,
                    919,
                    920,
                    921,
                    922,
                    923,
                    924,
                    925,
                    926,
                    927,
                    928,
                    929,
                    930,
                    931,
                    932,
                    933,
                    934,
                    935,
                    936,
                    937,
                    938,
                    939,
                    940,
                    941,
                    942,
                    943,
                    944,
                    945,
                    946,
                    947,
                    948,
                    949,
                    950,
                    951,
                    952,
                    953,
                    954,
                    955,
                    956,
                    957,
                    958,
                    959,
                    960,
                    961,
                    962,
                    963,
                    964,
                    965,
                    966,
                    967,
                    968,
                    969,
                    970,
                    971,
                    972,
                    973,
                    974,
                    975,
                    976,
                    977,
                    978,
                    979,
                    980,
                    981,
                    982,
                    983,
                    984,
                    985,
                    986,
                    987,
                    988,
                    989,
                    990,
                    991,
                    992,
                    993,
                    994,
                    995,
                    996,
                    997,
                    998,
                    999
                });

            migrationBuilder.InsertData(
                schema: "User",
                table: "Languages",
                columns: new[] { "ID", "Culture", "Description", "Direction", "LanguageName" },
                values: new object[,]
                {
                    { 1, "en-US", "English", "LTR", "en" },
                    { 2, "ar-SA", "Arabic", "RTL", "ar" }
                });

            migrationBuilder.InsertData(
                schema: "User",
                table: "DictionaryLocalizations",
                columns: new[] { "ID", "LanguageID", "Description" },
                values: new object[,]
                {
                    { 1, 1, "Welcome" },
                    { 1, 2, "مرحباً" },
                    { 2, 1, "Continue" },
                    { 2, 2, "متابعة" },
                    { 3, 1, "Next" },
                    { 3, 2, "التالي" },
                    { 4, 1, "Back" },
                    { 4, 2, "رجوع" },
                    { 5, 1, "Submit" },
                    { 5, 2, "إرسال" },
                    { 6, 1, "Verify" },
                    { 6, 2, "تحقق" },
                    { 7, 1, "Resend" },
                    { 7, 2, "إعادة إرسال" },
                    { 8, 1, "Complete" },
                    { 8, 2, "إكمال" },
                    { 20, 1, "Registration Steps" },
                    { 20, 2, "خطوات التسجيل" },
                    { 21, 1, "Personal Information" },
                    { 21, 2, "المعلومات الشخصية" },
                    { 22, 1, "Mobile Verification" },
                    { 22, 2, "التحقق من الجوال" },
                    { 23, 1, "Email Verification" },
                    { 23, 2, "التحقق من البريد الإلكتروني" },
                    { 24, 1, "Policy Approval" },
                    { 24, 2, "الموافقة على السياسة" },
                    { 25, 1, "PIN Setup" },
                    { 25, 2, "إعداد الرقم السري" },
                    { 26, 1, "Biometric Setup" },
                    { 26, 2, "إعداد البيانات الحيوية" },
                    { 27, 1, "Completed" },
                    { 27, 2, "مكتمل" },
                    { 30, 1, "Enter your personal details" },
                    { 30, 2, "أدخل بياناتك الشخصية" },
                    { 31, 1, "Verify your mobile number" },
                    { 31, 2, "تحقق من رقم جوالك" },
                    { 32, 1, "Verify your email address" },
                    { 32, 2, "تحقق من عنوان بريدك الإلكتروني" },
                    { 33, 1, "Accept terms and conditions" },
                    { 33, 2, "اقبل الشروط والأحكام" },
                    { 34, 1, "Create your security PIN" },
                    { 34, 2, "أنشئ رقمك السري للحماية" },
                    { 35, 1, "Set up biometric authentication" },
                    { 35, 2, "قم بإعداد المصادقة البيومترية" },
                    { 36, 1, "Registration completed successfully" },
                    { 36, 2, "تم إكمال التسجيل بنجاح" },
                    { 50, 1, "IC Number" },
                    { 50, 2, "رقم الهوية" },
                    { 51, 1, "Full Name" },
                    { 51, 2, "الاسم الكامل" },
                    { 52, 1, "Email Address" },
                    { 52, 2, "البريد الإلكتروني" },
                    { 53, 1, "Phone Number" },
                    { 53, 2, "رقم الهاتف" },
                    { 54, 1, "Language" },
                    { 54, 2, "اللغة" },
                    { 70, 1, "Enter OTP" },
                    { 70, 2, "أدخل رمز التحقق" },
                    { 71, 1, "OTP sent to your mobile" },
                    { 71, 2, "تم إرسال رمز التحقق إلى جوالك" },
                    { 72, 1, "OTP expired" },
                    { 72, 2, "انتهت صلاحية رمز التحقق" },
                    { 73, 1, "Invalid OTP" },
                    { 73, 2, "رمز تحقق غير صحيح" },
                    { 74, 1, "OTP verified successfully" },
                    { 74, 2, "تم التحقق من الرمز بنجاح" },
                    { 75, 1, "Resend OTP" },
                    { 75, 2, "إعادة إرسال الرمز" },
                    { 80, 1, "Terms and Conditions" },
                    { 80, 2, "الشروط والأحكام" },
                    { 81, 1, "Privacy Policy" },
                    { 81, 2, "سياسة الخصوصية" },
                    { 82, 1, "I agree to the terms and conditions" },
                    { 82, 2, "أوافق على الشروط والأحكام" },
                    { 83, 1, "Policy accepted" },
                    { 83, 2, "تم قبول السياسة" },
                    { 90, 1, "Create PIN" },
                    { 90, 2, "إنشاء الرقم السري" },
                    { 91, 1, "Confirm PIN" },
                    { 91, 2, "تأكيد الرقم السري" },
                    { 92, 1, "Unmatched PIN" },
                    { 92, 2, "الأرقام السرية غير متطابقة" },
                    { 93, 1, "PIN created successfully" },
                    { 93, 2, "تم إنشاء الرقم السري بنجاح" },
                    { 94, 1, "Enter 6-digit PIN" },
                    { 94, 2, "أدخل الرقم السري المكون من 6 أرقام" },
                    { 100, 1, "Enable Biometric Authentication" },
                    { 100, 2, "تفعيل المصادقة البيومترية" },
                    { 101, 1, "Biometric Setup" },
                    { 101, 2, "إعداد البيانات الحيوية" },
                    { 102, 1, "Face ID" },
                    { 102, 2, "التعرف على الوجه" },
                    { 103, 1, "Touch ID" },
                    { 103, 2, "بصمة اللمس" },
                    { 104, 1, "Biometric authentication enabled" },
                    { 104, 2, "تم تفعيل المصادقة البيومترية" },
                    { 105, 1, "Skip Biometric" },
                    { 105, 2, "تخطي البيانات الحيوية" },
                    { 120, 1, "Personal information saved" },
                    { 120, 2, "تم حفظ المعلومات الشخصية" },
                    { 121, 1, "Mobile number verified" },
                    { 121, 2, "تم التحقق من رقم الجوال" },
                    { 122, 1, "Email verified" },
                    { 122, 2, "تم التحقق من البريد الإلكتروني" },
                    { 123, 1, "Registration completed successfully" },
                    { 123, 2, "تم إكمال التسجيل بنجاح" },
                    { 124, 1, "Validation error" },
                    { 124, 2, "خطأ في التحقق" },
                    { 125, 1, "This field is required" },
                    { 125, 2, "هذا الحقل مطلوب" },
                    { 126, 1, "Invalid IC Number" },
                    { 126, 2, "رقم هوية غير صحيح" },
                    { 127, 1, "IC Number already exists" },
                    { 127, 2, "رقم الهوية موجود مسبقاً" },
                    { 140, 1, "Enter your IC Number" },
                    { 140, 2, "أدخل رقم الهوية" },
                    { 141, 1, "Enter your full name" },
                    { 141, 2, "أدخل اسمك الكامل" },
                    { 142, 1, "Enter your email" },
                    { 142, 2, "أدخل بريدك الإلكتروني" },
                    { 143, 1, "Enter your phone number" },
                    { 143, 2, "أدخل رقم هاتفك" },
                    { 144, 1, "Select your language" },
                    { 144, 2, "اختر لغتك" },
                    { 145, 1, "This field is required and Length is between {0} and {1}" },
                    { 145, 2, "هذا الحقل مطلوب ويجب ان يكون عدد الخانات بين {0} و {1}" },
                    { 146, 1, "Please enter a valid e-mail address" },
                    { 146, 2, "الرجاء ادخال بريد الكتروني صالح" },
                    { 147, 1, "Please enter a valid phone number" },
                    { 147, 2, "الرجاء إدخال رقم هاتف صالح" },
                    { 173, 1, "The email address is already in use" },
                    { 173, 2, "البريد الإلكتروني مستخدم بالفعل" },
                    { 174, 1, "Invalid email address" },
                    { 174, 2, "بريد إلكتروني غير صالح" },
                    { 175, 1, "The password is too short" },
                    { 175, 2, "كلمة المرور قصيرة جدًا" },
                    { 176, 1, "The password must contain a symbol" },
                    { 176, 2, "يجب أن تحتوي كلمة المرور على رمز" },
                    { 177, 1, "The password must contain a digit" },
                    { 177, 2, "يجب أن تحتوي كلمة المرور على رقم" },
                    { 178, 1, "Invalid OTP" },
                    { 178, 2, "رمز تحقق غير صحيح" },
                    { 179, 1, "The password must contain an uppercase letter" },
                    { 179, 2, "يجب أن تحتوي كلمة المرور على حرف كبير" },
                    { 180, 1, "Invalid registration step" },
                    { 180, 2, "خطوة تسجيل غير صحيحة" },
                    { 181, 1, "OTP expired" },
                    { 181, 2, "انتهت صلاحية رمز التحقق" },
                    { 182, 1, "An unknown error occurred" },
                    { 182, 2, "حدث خطأ غير معروف" },
                    { 183, 1, "Please enter your OTP again " },
                    { 183, 2, "يرجى إدخال رمز التحقق مرة أخرى" },
                    { 184, 1, "There's an account registered with the IC number. Please login to continue" },
                    { 184, 2, "يوجد حساب مسجل برقم الهوية. يرجى تسجيل الدخول للمتابعة" },
                    { 185, 1, "Please enter your PIN again " },
                    { 185, 2, "يرجى إدخال الرقم السري مرة أخرى" }
                });

            migrationBuilder.CreateIndex(
                name: "IX_AspNetRoleClaims_RoleId",
                schema: "User",
                table: "AspNetRoleClaims",
                column: "RoleId");

            migrationBuilder.CreateIndex(
                name: "RoleNameIndex",
                schema: "User",
                table: "AspNetRoles",
                column: "NormalizedName",
                unique: true,
                filter: "[NormalizedName] IS NOT NULL");

            migrationBuilder.CreateIndex(
                name: "IX_AspNetUserClaims_UserId",
                schema: "User",
                table: "AspNetUserClaims",
                column: "UserId");

            migrationBuilder.CreateIndex(
                name: "IX_AspNetUserLogins_UserId",
                schema: "User",
                table: "AspNetUserLogins",
                column: "UserId");

            migrationBuilder.CreateIndex(
                name: "IX_AspNetUserRoles_RoleId",
                schema: "User",
                table: "AspNetUserRoles",
                column: "RoleId");

            migrationBuilder.CreateIndex(
                name: "EmailIndex",
                schema: "User",
                table: "AspNetUsers",
                column: "NormalizedEmail");

            migrationBuilder.CreateIndex(
                name: "IX_AspNetUsers_Id_LanguageID",
                schema: "User",
                table: "AspNetUsers",
                columns: new[] { "Id", "LanguageID" });

            migrationBuilder.CreateIndex(
                name: "UserNameIndex",
                schema: "User",
                table: "AspNetUsers",
                column: "NormalizedUserName",
                unique: true,
                filter: "[NormalizedUserName] IS NOT NULL");

            migrationBuilder.CreateIndex(
                name: "IX_DictionaryLocalizations_LanguageID",
                schema: "User",
                table: "DictionaryLocalizations",
                column: "LanguageID");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "AspNetRoleClaims",
                schema: "User");

            migrationBuilder.DropTable(
                name: "AspNetUserClaims",
                schema: "User");

            migrationBuilder.DropTable(
                name: "AspNetUserLogins",
                schema: "User");

            migrationBuilder.DropTable(
                name: "AspNetUserRoles",
                schema: "User");

            migrationBuilder.DropTable(
                name: "AspNetUserTokens",
                schema: "User");

            migrationBuilder.DropTable(
                name: "DictionaryLocalizations",
                schema: "User");

            migrationBuilder.DropTable(
                name: "AspNetRoles",
                schema: "User");

            migrationBuilder.DropTable(
                name: "AspNetUsers",
                schema: "User");

            migrationBuilder.DropTable(
                name: "Dictionaries",
                schema: "User");

            migrationBuilder.DropTable(
                name: "Languages",
                schema: "User");
        }
    }
}
